typography_spectrum: 0.8880380592308939
color:
  brandStrength: 0.8553191
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
  brandColors:
    - '#CFDDE3'
    - '#150608'
    - '#9C0C11'
    - '#B89B73'
    - '#544A4C'
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5489362
analytics:
  facebook: null
  google: null
  twitter: null
name: Renold Beratung
cta:
  domain: null
  version: null
  bucket: null
navigation:
  - name: theater anundpfirsich
    url: 'https://www.pfirsi.ch'
    type: external
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Renold Beratung
purpose: []
