name: Renold Beratung
favicon: null
layout_spectrum: 0.29040258983150125
typography_spectrum: 0.8880380592308939
title: Renold Beratung
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdf6'
    - '#0a1416'
    - '#343f41'
    - '#6a5f43'
    - '#c1a75e'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
