title: Renold Beratung
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.2904025898315012
favicon: null
name: Renold Beratung
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8553191
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
  brandColors:
    - '#160C0A'
    - '#FFFFFF'
    - '#FFB477'
    - '#FFFBA3'
    - '#885C42'
typography_spectrum: 0.8880380592308939
